Experiment with HarfBuzz regression testing
googlefonts/googlesans pull request #137
Opened 2021-01-26 12:08 UTC by madig

---

@chrissimpkins edits below

### TODO

- [x] add direction parameter to support hb buffer direction configuration for RTL scripts?
- [x] add maintainer docs (or open issue to add in a separate PR) - added in #140 
- [x] Is uHB going to be maintained?, who is the primary maintainer?, is it the best project to base our shaping regression strategy on?

2021-01-26 12:29 UTC, belluzj commented on qa/shaping/armenian/ccmp.txt
> +Է՞է՞ Ե՞ե՞ և՞
I like the idea of 1 file/test case, with matching names but different extensions for the input and output. You could glob for all such files in the fontbakery test.

However I think .txt as an input format will prove limiting, as in this case you're specifying ccmp: true in the fontbakery check, it could be put in this file if it was toml or yaml.

```toml
string = "Է՞է՞ Ե՞ե՞ և՞"
comment = "Test that blabla (not mandatory but could be nice to write if what we're testing is not obvious)"
[features]
ccmp = true
```

2021-01-26 12:51 UTC, belluzj commented on qa/check-fea.py
> +def com_google_fonts_check_googlesans_features_armenian_min_opsz(ttFont):
My approach here would be to glob all the folders recursively, for all scripts (not just Armenian), but I don't know from the fontbakery perspective, is that OK to have one check that goes through a massive list of asserts? Also, you might want to have some tests run only on italic files, or only on the variable font etc. (I see that this current tests says "is_not_italic", "is_not_variable_font"). Could you put that in the TOML files of the test inputs?

Also at some point we said that maybe we could always check the variable font and the statics at the same locations to make sure that both match. Should this be automatic?

Also, given 1 input string, we might want to have several outputs depending on the location in the designspace (more weight = different x/y positions of glyphs; different opsz = different glyph names because of conditional glyphs). How to encode that into the output file? 1 big JSON such as below? Smaller JSONs for each location, with the location in the file name?

```json
[
  {
    "location": {
      "wght": 100,
      "opsz": 17
    },
    "output": [
      {
        "glyph": "uni0537",
        "cluster": 0,
        "x_offset": 0,
        "y_offset": 0,
        "x_advance": 619,
        "y_advance": 0
      },
      ...
    ]
  },
  {
    "location": {
      "wght": 400,
      "opsz": 17
    },
    "output": [...]
  },
  ...
]
```

2021-01-26 12:55 UTC, belluzj commented on qa/check-fea.py
> +            "glyph": font.get_glyph_name(info.codepoint),
For a second I was concerned this line wouldn't return the right glyph names because I thought "the glyphs from features won't have a code point" but it looks like from your example that it works for `uni055E.cap.comb` which I suspect doesn't have a code point?

2021-01-26 12:56 UTC, belluzj commented on qa/harfbuzz.py
> +        "--features", help="Comma-separated feature list like `ccmp=true,smcp=false`"
The features should be in the input files

2021-01-26 12:58 UTC, belluzj commented on qa/harfbuzz.py
> +    parser.add_argument("font_path", type=Path)
I also think the information about which fonts can be checked with this input file should be in the input file, as conditions such as the fontbakery stuff (is_italic, is_not_variable...)

2021-01-26 12:59 UTC, belluzj commented on qa/harfbuzz.py
> +    parser.add_argument("text_path", type=Path)
rename to input path. Take several entries at once so we can glob in the shell to regenerate a bunch of files at once.

2021-01-26 13:02 UTC, belluzj commented on qa/harfbuzz.py
> +from typing import Any, Dict, List
Maybe rename this script to "update_shaping_test_data" or something like that?

2021-01-26 13:05 UTC, belluzj commented on qa/check-fea.py
> +def com_google_fonts_check_googlesans_features_armenian_min_opsz(ttFont):
Note: "location" is good if you test the VF but not if you test a static weight

```json
{
  "file": "GoogleSans-Regular.ttf",
},
{
  "file": "GoogleSans[opsz,wght].ttf",
  "location": {
    "opsz": 17,
    ...
```

2021-01-26 13:05 UTC, belluzj commented on qa/check-fea.py
> +def com_google_fonts_check_googlesans_features_armenian_min_opsz(ttFont):
Note: shaping between static weight and VF can be off-by-one?

2021-01-26 13:09 UTC, chrissimpkins commented on qa/check-fea.py
> +def com_google_fonts_check_googlesans_features_armenian_min_opsz(ttFont):
> but I don't know from the fontbakery perspective, is that OK to have one check that goes through a massive list of asserts

It is so long as there is informative output when any of the assertions fail and the test is structured so that all assertions run with the FAIL raised at the end of testing + all failed tests in the report.

Is going with pytest a better approach for the shaping regression tests?  If that is a better solution so that we have access to parameterization, fixtures, etc. or to address issues like:

> NOTE: copy-pasta from harfbuzz.py because fontbakery doesn't knwo how to import it.

 we could do that.

2021-01-26 13:10 UTC, madig commented on qa/check-fea.py
> +            "glyph": font.get_glyph_name(info.codepoint),
HarfBuzz works with glyph ids and can reconstruct the name somehow, the glyph in question does not have a codepoint.

2021-01-26 13:29 UTC, madig commented on qa/check-fea.py
> +def com_google_fonts_check_googlesans_features_armenian_min_opsz(ttFont):
Jany and me found that it's probably better to keep expected shaping results separate for statics and VFs as they differ in glyph set. The bracket glyphs are standalone in VFs but are swapped into their target glyphs in the statics. This will show up in HarfBuzz's output.

I think going with fontbakery is fine, as the error messages can contain the file name and the input that failed. I'll continue experimentation.

2021-01-29 11:46 UTC, belluzj commented
I see that you've put the input and the output in the same text file? I'm not sure that's a great idea; I would at least separate them a bit better with top-level keys `input: { text:, features: }, output: { GoogleSansRg: ... }`

(the idea being that the input should be easy to edit by hand, and the output not so much. As soon as one file will have a full sentence of input, the output section will be gigantic and editing that file will be annoying)

2021-01-29 11:47 UTC, belluzj commented
Otherwise, I think you're ready to add all the data from Gor's test page and see whether the system you've put in place is handy to use

2021-01-29 14:27 UTC, madig commented
@chrissimpkins ping. What do you think? I dub these HarfBuzz unit tests.

I'd write a json file with the `input` stuff and fill it in with `python qa/update_shaping_test_data.py myfile.json build/GoogleSans/variable/expert/*.ttf build/GoogleSans/static/expert/*.ttf`. What would need some more thinking is how to display errors. We had the idea that fontbakery could create HTML pages that sort of look like what Gor provided and mark diffs in red.

2021-01-29 15:20 UTC, madig commented
(The newly imported changes change shaping output)

2021-02-01 11:47 UTC, madig commented
@chrissimpkins ping :)

I had the idea to add some shaping options. Sometimes, you don't care about advance widths or offsets but only about the raw glyph name stream (i.e. for `rvrn` testing) 🤔

2021-02-02 03:29 UTC, chrissimpkins requested changes
This is a fantastic idea Nikolaus and Jany.  I love it.  I have a handful of comments inline.  The fontbakery json test file loop and direction parameter may need to be addressed.  Let me know what you think.

One other general comment. It looks like uharfbuzz is on HB v2.7.2 (HB v2.7.3 is in master branch since December but not released to PyPI yet) and harfbuzz is at v2.7.4. Let's discuss how important HB and uHB versions are in our testing.  It looks like uHB is doing some Python-y/Cython-y things that lead to releases off of the HB release cycle.  We'll either need to decide that we want to let the uHB version float to the latest version or add this to a maintainer todo list for a periodic maintenance version bump.  Unless there is a reason to pin the version, I suggest that we support the former.  If there is a reason to pin it, then I'll emphasize the comment about moving the dependency to a requirements-dev.txt file so that we can run pip-compile on the file and not have all of our build dependencies update at the same time. 

And lastly, we should make sure that someone plans to maintain uHB if we are going to build our shaping regression tests around the project.   @davelab6 @anthrotype

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +            yield FAIL, f"Expected and actual shaping not matching for {shaping_file}."
Worth tossing a [difflib.unified_diff](https://docs.python.org/3/library/difflib.html#difflib.unified_diff) in here?  Then we know what the diff is in CI output without needing to manually build files, dump the shaping data and diff against the expected data.

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +            yield PASS, "No regression detected"
I think that this test exits your `for shaping_file in shaping_basedir.glob("*.json")` loop on the initial pass through it.  I need to keep going to understand what is in the separate shaping json files that are being iterated through.  Possibly by script area?

I think that we may need to pull this out of the loop and maintain the fails in a data structure, then yield the PASS or FAIL after all json files are tested and we know the status across all tests.

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +    NOTE: copy-pasta from harfbuzz.py because fontbakery doesn't know how to import it.
Will you point me to the location of this file so that I can have a look at the license?

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +    variations: Optional[Dict[str, float]] = None,
define var font designspace slice with {'axis tag': float, 'axis tag': float} here?

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +    features: Dict[str, bool],
`{'fea tag': True}` to activate optional features?

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +            yield PASS, "No regression detected"
OK I see now. Yeah, the json files are divided up by script and feature.  I think that this runs once per font and tests against the first json file path returned by `shaping_basedir.glob("*.json")` then exits the loop when you yield the PASS/FAIL.

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +    variations: Optional[Dict[str, float]] = None,
Got it, this is the TTFont fvar table `instance.coordinates` format: `{'opsz': 18.0, 'wght': 400.0}`

2021-02-02 03:29 UTC, chrissimpkins commented on qa/check-fea.py
> +def shape_text(
We need a direction parameter too to support Hebrew tests (and to future proof for other RTL scripts coming soon)?

2021-02-02 03:29 UTC, chrissimpkins commented on qa/shaping/armenian_c2sc.json
> +    "script": "armn",
This is the correct way to define script/lang in multi-script text runs? 🤔

2021-02-02 03:29 UTC, chrissimpkins commented on qa/update_shaping_test_data.py
> +def shape_text(
Same comment as above in the fontbakery profile source.  Do we need a direction parameter for RTL scripts?

From [Harfbuzz docs](https://harfbuzz.github.io/setting-buffer-properties.html):

> Buffers also need to carry information about the script, language, and text direction of their contents. You can set these properties individually:

```cpp
      hb_buffer_set_direction(buf, HB_DIRECTION_LTR);
      hb_buffer_set_script(buf, HB_SCRIPT_LATIN);
      hb_buffer_set_language(buf, hb_language_from_string("en", -1));
```

2021-02-02 03:29 UTC, chrissimpkins commented on requirements.txt
> +uharfbuzz==0.14.0
Not a build dependency and we don't include fontbakery in the requirements.txt file.  Want to stick the uharfbuzz  install in the GH Actions configuration or pull it out into a requirements-dev.txt file?  We can add the requirements-dev.txt installs to a dev venv build Makefile target.

We want the fontbakery version to float to new releases in order to automatically pick up new tests, bug fixes.  How important is it that we pin the uharfbuzz version rather than taking latest for these tests?

2021-02-02 04:01 UTC, chrissimpkins commented
We'll need to add maintainer documentation to `docs/MAINTAINER.md` also.  Can be done in a separate PR.  I'll get #120 merged first and then we can address it.

2021-02-02 10:09 UTC, madig commented on qa/check-fea.py
> +    NOTE: copy-pasta from harfbuzz.py because fontbakery doesn't know how to import it.
Ah, that comment is stale. Basically I have to copy the code from `update_shaping_test_data.py` into `check-fea.py` because fontbakery trips over itself trying to import it.

2021-02-02 10:09 UTC, madig commented on qa/shaping/armenian_c2sc.json
> +    "script": "armn",
I don't know :D

2021-02-02 10:56 UTC, madig commented on requirements.txt
> +uharfbuzz==0.14.0
Let's do a requirements-dev.txt. Can I add that to the `setup` Makefile target or is that just for production builds?

2021-02-02 10:56 UTC, madig commented on qa/update_shaping_test_data.py
> +def shape_text(
Will implement that then.

2021-02-02 11:22 UTC, madig commented on qa/check-fea.py
> +            yield PASS, "No regression detected"
Hm? It yields pass/fail for every json file for every font. Check with `fontbakery check-profile -c regression -C --loglevel PASS qa/check-fea.py build/GoogleSans/variable/expert/*.ttf build/GoogleSans/static/expert/*.ttf`.

2021-02-02 11:47 UTC, madig commented on qa/check-fea.py
> +            yield FAIL, f"Expected and actual shaping not matching for {shaping_file}."
I now generate HTML diff pages. Very rough, but gives you an idea.

2021-02-02 13:09 UTC, chrissimpkins commented on qa/check-fea.py
> +    NOTE: copy-pasta from harfbuzz.py because fontbakery doesn't know how to import it.
So nothing is coming from licensed source in an external project?  If so, we are ok here.

2021-02-02 13:12 UTC, chrissimpkins commented on qa/check-fea.py
> +            yield PASS, "No regression detected"
OK, sgtm. I was under the impression that fontbakery behaves differently. Thanks Nikolaus.

2021-02-02 13:25 UTC, chrissimpkins commented
@simoncozens Nikolaus is developing a uHarfbuzz based shaping regression test approach via shaping string diffs.  This will include a collection of "important" text runs that should be checked for shaping regressions as we update the sources with all of the new i18n design work.  Are you willing to review this PR and weigh in on with your thoughts about the approach?

2021-02-02 13:26 UTC, chrissimpkins commented on qa/shaping/armenian_c2sc.json
> +    "script": "armn",
Let's leave this unresolved for now.

2021-02-02 13:26 UTC, chrissimpkins commented on requirements.txt
> +uharfbuzz==0.14.0
`setup` target is OK by me.  Thanks Nikolaus

2021-02-02 13:28 UTC, chrissimpkins commented on requirements.txt
> +uharfbuzz==0.14.0
Any thoughts about how to handle the uHB version? Pin or not?

2021-02-02 13:32 UTC, chrissimpkins commented on qa/check-fea.py
> +            yield FAIL, f"Expected and actual shaping not matching for {shaping_file}."
> I now generate HTML diff pages. Very rough, but gives you an idea.

Are you thinking that we might run into massive diffs that are difficult to view in the GitHub UI CI output window?  If not, IMO the better approach would be to support the diff as unified diff text in the fontbakery CI output rather than requiring this to be run locally in order to understand what is different.  Or are you thinking that we push those HTML pages somewhere that allows them to be downloaded?

2021-02-02 13:41 UTC, simoncozens commented
Interesting - as you know I've been working on exactly the same thing! (https://github.com/simoncozens/nastaliq-engineering/blob/master/gnipahs.py)

I'll look in detail later but a few initial thoughts:

* This could be added to fontbakery; it's not something that's terribly GS-specific.
* JSON seems a bit heavy. If you serialise the buffer in a way that's compatible with hb-shape (see https://github.com/simoncozens/font-engineering/blob/49bede2d535bff8b35b634df4978fbc87561d726/vharfbuzz.py#L87-L97) then your test files are shorter and easier to read, and you have more flexibility in terms of generating the testing expectations.
* You don't need to pass direction or script just to get e.g. RTL support; `guess_segment_properties` does that.
* Features should take a feature string (for partial application), or at least allow for integers as well as booleans (alternates' tc.)
* Probably better to make the `hb.Face`/`hb.Font`/etc. a fixture rather than pulling in the font every time.

2021-02-02 13:50 UTC, madig commented
Thanks for reviewing! I agree that this would be nice to have in FB, my intention was to come up with something first and generalize later. I'd be fine with dropping this in favor of whatever you are working on if you target FB upstream.

2021-02-02 14:09 UTC, simoncozens commented
No, this is good and much more thorough than mine. OK, we'll polish it here then turn it into a FB PR.

2021-02-02 15:16 UTC, chrissimpkins commented
Thank you very much Simon. Much appreciated.  

> This could be added to fontbakery; it's not something that's terribly GS-specific.

Definitely agree. There are likely to also be generalizable shaping issue text runs across those that we will collect for the scripts in this project. It would be worth figuring out a way to export those out of this project so that others can use them with whatever approach is developed in fontbakery or elsewhere.  

For now we need an approach that gets the job done here to move ahead with script merges.  Let's continue the discussion about how to move it out of the GS repo.

2021-02-02 15:22 UTC, simoncozens requested changes

2021-02-02 15:22 UTC, simoncozens commented on qa/check-fea.py
> +            shaping_script = shaping_input["script"]
Suggest making these two optional, as Harfbuzz can guess them if they're not provided. (Normally they wouldn't be provided when shaping, unless you're testing `locl` stuff.)

2021-02-02 15:22 UTC, simoncozens commented on qa/check-fea.py
> +            shaped_texts = shape_variable(
Avoid repetition here:

```
if "fvar" in tt:
    shape_function = shape_variable
else:
    shape_function = shape_static

shaped_text = shape_function(...)
```

2021-02-02 15:22 UTC, simoncozens commented on qa/check-fea.py
> +            shaped_texts_json = json.dumps(shaped_texts, indent=2).split("\n")
Serializing the buffer to hb-shape-like strings would make this tidier and easier for end-user to read.

2021-02-02 15:22 UTC, simoncozens commented on qa/check-fea.py
> +    hb.ot_font_set_funcs(font)
Suggest making this a FontBakery condition rather than re-setting it up for each string.

2021-02-02 15:22 UTC, simoncozens commented on qa/check-fea.py
> +def shape_variable(
I'm really suspicious of the repetition in these two functions. They're basically the same, and most of the code is taken up with unpacking parameter lists and packing them up again. Maybe you should be passing a parameters hash initially, or maybe you should be making more use of `kwargs`.

2021-02-02 15:22 UTC, simoncozens commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
That seems like a problem worth solving. There should be a generic shaping library (see my Vharfbuzz), which both this and the `update_shaping_test_data` uses.

2021-02-02 15:48 UTC, madig commented on qa/check-fea.py
> +            shaping_script = shaping_input["script"]
Cosimo suggested requiring them to rule out HB misguessing.

2021-02-02 15:51 UTC, simoncozens commented on qa/check-fea.py
> +            shaping_script = shaping_input["script"]
HB guessing wrong is an argument for *allowing* them, but you only need to supply them when HB *does* guess wrong. (But does it really guess wrong? Do we have examples of this happening?)

2021-02-02 15:54 UTC, madig commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
The problem is that doing `from .update_shaping_test_data import *` results in FB keeling over:

```
Traceback (most recent call last):
  File "/home/nikolaus/googlesans/venv/bin/fontbakery", line 8, in <module>
    sys.exit(main())
  File "/home/nikolaus/googlesans/venv/lib/python3.8/site-packages/fontbakery/cli.py", line 21, in main
    runpy.run_module(
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nikolaus/googlesans/venv/lib/python3.8/site-packages/fontbakery/commands/check_profile.py", line 369, in <module>
    sys.exit(main())
  File "/home/nikolaus/googlesans/venv/lib/python3.8/site-packages/fontbakery/commands/check_profile.py", line 246, in main
    profile = get_profile()
  File "/home/nikolaus/googlesans/venv/lib/python3.8/site-packages/fontbakery/commands/check_profile.py", line 231, in get_profile
    imported = get_module(args.profile)
  File "/home/nikolaus/googlesans/venv/lib/python3.8/site-packages/fontbakery/commands/check_profile.py", line 213, in get_module
    imported = get_module_from_file(name)
  File "/home/nikolaus/googlesans/venv/lib/python3.8/site-packages/fontbakery/checkrunner.py", line 1916, in get_module_from_file
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "qa/check-fea.py", line 426, in <module>
    from .update_shaping_test_data import *
ModuleNotFoundError: No module named 'fontbakery.__file_modules'
```

Haven't had the nerve to dive into FB yet.

2021-02-02 16:14 UTC, simoncozens commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
OK, looks like FB has a problem with relative imports. Importing from "qa.update_shaping_test_data" (and setting PYTHONPATH) works fine. I'll raise a FB issue.

2021-02-02 16:14 UTC, madig commented on qa/check-fea.py
> +def shape_variable(
Golfed them a bit.

2021-02-02 16:22 UTC, simoncozens commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
https://github.com/googlefonts/fontbakery/issues/3161

2021-02-02 16:25 UTC, simoncozens commented
> Is uHB going to be maintained?

Yes. It's considered part of the Harfbuzz project.

> who is the primary maintainer?

Just, although the Harfbuzz maintainers can also commit to master.

> is it the best project to base our shaping regression strategy on?

Sure, what else is there? And now if it ever goes wrong, you can replace it with command-line call-outs to `hb-shape`.

2021-02-02 16:32 UTC, madig commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
With `from qa.update_shaping_test_data import ...` I get `ModuleNotFoundError: No module named 'qa'` :(

2021-02-02 16:35 UTC, madig commented on qa/check-fea.py
> +            shaping_script = shaping_input["script"]
I have zero idea! I am however obsessed with edge cases. But can make optional, as well as direction.

2021-02-02 16:38 UTC, simoncozens commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
`PYTHONPATH=.` (or in the Makefile `export PYTHONPATH=.`)

2021-02-02 16:55 UTC, madig commented on qa/check-fea.py
> +# XXX: Below is a copy-pasta of update_shaping_test_data.py because I can't
Or inside the .py file actually :O ugly but works.

2021-02-02 17:41 UTC, chrissimpkins commented
>> is it the best project to base our shaping regression strategy on?

> Sure, what else is there? And now if it ever goes wrong, you can replace it with command-line call-outs to hb-shape.

Harfbuzz :)

2021-02-02 17:58 UTC, simoncozens commented
uHarfbuzz is the python wrapper around Harfbuzz. If you want to use Harfbuzz from Python, this is how you do it.

2021-02-02 18:28 UTC, madig commented on qa/check-fea.py
> +    hb.ot_font_set_funcs(font)
I put `hb.Face` into a condition now. Is `hb.Font` that other stuff a heavy op?

2021-02-02 18:29 UTC, chrissimpkins commented
> uHarfbuzz is the python wrapper around Harfbuzz. If you want to use Harfbuzz from Python, this is how you do it.

I think that this conversation originated from these statements that I made in https://github.com/googlefonts/googlesans/pull/137#pullrequestreview-580920035

> One other general comment. It looks like uharfbuzz is on HB v2.7.2 (HB v2.7.3 is in master branch since December but not released to PyPI yet) and harfbuzz is at v2.7.4. Let's discuss how important HB and uHB versions are in our testing. It looks like uHB is doing some Python-y/Cython-y things that lead to releases off of the HB release cycle. 

By "is this the best project", I meant the uHarfbuzz Python wrapper for Harfbuzz.  An alternative approach is to do all of this with Harfbuzz/ the hb-shape utility without accessing it via Python or using it in fontbakery.  I was thinking out loud.  I think that these questions remain.  How much does uHarfbuzz diverge from Harfbuzz now and in the future, is uHarfbuzz maintained on a release schedule (relative to Harfbuzz) that this remains a reliable approach for shaping regression testing in this project down the road? Do Harfbuzz versions really matter for this style of testing and how do we approach the version of the test dependency that we use?

2021-02-03 10:29 UTC, madig commented
I think the big draw with a Python wheel is that we can just `pip install` it anywhere without messing with compilers. We don't seem to be missing too much when staying on 2.7.2, but maybe we can budget some time for uHB maintenance? I see it's still on Travis and Appveyor, and could also do with some typing stubs. Typical housekeeping stuff.

2021-02-03 10:41 UTC, madig commented
(Awaiting further reviews. Or are the unit tests ready to go after we decided on HB or uHB?)

2021-02-03 10:43 UTC, madig commented on requirements.txt
> +uharfbuzz==0.14.0
Hm. I think we can leave unpinned and revisit if problems crop up.

2021-02-03 10:46 UTC, madig commented
Oh wait. generating HTML diffs and writing them to temp is ok locally but problematic on the CI... except maybe if they are uploaded as artifacts?

2021-02-03 11:06 UTC, simoncozens commented
This is why I suggested using the hb-shape strings and diffing those: you can do it as a textual diff, and add that to the normal FB report.

2021-02-03 11:12 UTC, madig commented
Hm. I worry about readability on the command line. Well, I'll try something and see if it's acceptable.

2021-02-03 11:24 UTC, simoncozens commented
If the tests pass, it'll be readable. If the tests don't pass, you don't *want* readable, you want detailed enough to diagnose and fix.

> We don't seem to be missing too much when staying on 2.7.2, but maybe we can budget some time for uHB maintenance?
> I see it's still on Travis and Appveyor, and could also do with some typing stubs.

Moving to GitHub actions would be good; I think if that's done, we can work on automatically sync'ing the Harfbuzz versions and doing. a new release every time HB is released. (See https://github.com/harfbuzz/harfbuzz/issues/2839) That would cut the maintenance burden considerably.

2021-02-03 11:50 UTC, madig commented
Report looks like this now:

```
 >> com.google.fonts/check/googlesans/features/regression
    But does it shape?
    with build/GoogleSans/variable/expert/GoogleSans-Italic[opsz,wght].ttf

    * FAIL: qa/shaping/armenian_case.json: Expected and actual shaping not matching.
        Expected for opsz=18.0,wght=400.0:
          uni055A.BRACKET.18=0+228,0|uni053B=1+637,0|space=2+224,0|Ech_Vewarm.liga=3+1282,0|uni055D=4+255,0|space=5+224,0|uni0544=6+665,0|uni0589.case=7+239,0
          Men_Nowarm.liga=0+1331,0|space=1+224,0|Men_Echarm.liga=2+1398,0|space=3+224,0|Men_Iniarm.liga=4+1381,0|space=5+224,0|Vew_Nowarm.liga=6+1294,0|space=7+224,0|Men_Xeharm.liga=8+1601,0
          Ech_Vewarm.liga=0+1312,0|uni055B.comb=1@-1097,0|space=2+224,0|Men_Echarm.liga=3+1398,0|uni055B.comb=4@-398,0|space=5+224,0|Men_Iniarm.liga=6+1381,0|uni055B.short.comb=7@-388,0
        Actual:
          uni055A.BRACKET.18=0+228,0|uni053B=1+637,0|space=2+224,0|Ech_Vewarm.liga=3+1282,0|uni055D=4+255,0|space=5+224,0|uni0544=6+665,0|uni0589.case=7+239,0
          Men_Nowarm.liga=0+1331,0|space=1+224,0|Men_Echarm.liga=2+1398,0|space=3+224,0|Men_Iniarm.liga=4+1381,0|space=5+224,0|Vew_Nowarm.liga=6+1294,0|space=7+224,0|aMen_Xeharm.liga=8+1601,0
          Ech_Vewarm.liga=0+1312,0|uni055B.comb=1@-1097,0|space=2+224,0|Men_Echarm.liga=3+1398,0|uni055B.comb=4@-398,0|space=5+224,0|Men_Iniarm.liga=6+1381,0|uni055B.short.comb=7@-388,0
    * FAIL: qa/shaping/armenian_case.json: Expected and actual shaping not matching.
        Expected for opsz=17.0,wght=400.0:
          uni055A.case=0+292,0|uni053B=1+640,0|space=2+256,0|Ech_Vewarm.liga=3+1347,0|uni055D=4+254,0|space=5+256,0|uni0544=6+705,0|uni0589.case=7+259,0
          Men_Nowarm.liga=0+1352,0|space=1+256,0|Men_Echarm.liga=2+1476,0|space=3+256,0|Men_Iniarm.liga=4+1425,0|space=5+256,0|Vew_Nowarm.liga=6+1357,0|space=7+256,0|Men_Xeharm.liga=8+1674,0
          Ech_Vewarm.liga=0+1427,0|uni055B.comb=1@-1213,0|space=2+256,0|Men_Echarm.liga=3+1476,0|uni055B.comb=4@-477,0|space=5+256,0|Men_Iniarm.liga=6+1425,0|uni055B.short.comb=7@-401,0
        Actual:
          uni055A.case=0+292,0|uni053B=1+640,0|space=2+256,0|Ech_Vewarm.liga=3+1347,0|uni055D=4+254,0|space=5+256,0|uni0544=6+705,0|uni0589.case=7+259,0
          Men_Nowarm.liga=0+1352,0|sapace=1+256,0|Men_Echarm.liga=2+1476,0|space=3+256,0|Men_Iniarm.liga=4+1425,0|space=5+256,0|Vew_Nowarm.liga=6+1357,0|space=7+256,0|Men_Xeharm.liga=8+1674,0
          Ech_Vewarm.liga=0+1427,0|uni055B.comb=1@-1213,0|space=2+256,0|Men_Echarm.liga=3+1476,0|uni055B.comb=4@-477,0|space=5+256,0|Men_Iniarm.liga=6+1425,0|uni055B.short.comb=7@-401,0


    Result: FAIL

 >> com.google.fonts/check/googlesans/features/regression
    But does it shape?
    with build/GoogleSans/static/expert/GoogleSans-Regular.ttf

    * FAIL: qa/shaping/armenian_case.json: Expected and actual shaping not matching.
        Expected:
          uni055A.case=0+224,0|uni053B=1+637,0|space=2+232,0|Ech_Vewarm.liga=3+1280,0|uni055D=4+255,0|space=5+232,0|uni0544=6+664,0|uni0589.case=7+238,0
          Men_Nowarm.liga=0+1331,0|space=1+232,0|Men_Echarm.liga=2+1397,0|space=3+232,0|Men_Iniarm.liga=4+1381,0|space=5+232,0|Vew_Nowarm.liga=6+1295,0|space=7+232,0|Men_Xeharm.liga=8+1603,0
          Ech_Vewarm.liga=0+1310,0|uni055B.comb=1@-1098,0|space=2+232,0|Men_Echarm.liga=3+1397,0|uni055B.comb=4@-400,0|space=5+232,0|Men_Iniarm.liga=6+1381,0|uni055B.short.comb=7@-387,0
        Actual:
          uni055A.case=0+224,0|uni053B=1+637,0|space=2+232,0|Ech_Vewarm.liga=3+1280,0|uni055D=4+255,0|space=5+232,0|uni0544=6+664,0|uni0589.case=7+238,0
          Men_Nowarm.liga=0+1331,0|space=1+232,0|Men_Echarm.liga=2+1397,0|aspace=3+232,0|Men_Iniarm.liga=4+1381,0|space=5+232,0|Vew_Nowarm.liga=6+1295,0|space=7+232,0|Men_Xeharm.liga=8+1603,0
          Ech_Vewarm.liga=0+1310,0|uni055B.comb=1@-1098,0|space=2+232,0|Men_Echarm.liga=3+1397,0|uni055B.comb=4@-400,0|space=5+232,0|Men_Iniarm.liga=6+1381,0|uni055B.short.comb=7@-387,0


    Result: FAIL
```

2021-02-03 13:24 UTC, madig commented
What remains to be done here? I can clean up the commits and split the PR up, the core code can go to master and the amrn tests can be appended to the Armenian PR.

2021-02-03 13:26 UTC, chrissimpkins commented
> If the tests don't pass, you don't want readable, you want detailed enough to diagnose and fix.

I'd argue that it would be *ideal* to have it show exactly what differs rather than requiring a second step to pull out a block of text strings for a local diff.  But perfect is the enemy of good.  Let's get something in place that does the job and we can update further as we go along.  No need to get bogged down on making this a perfect solution right now.  The full observed / expected output LGTM.  And I really like that it is in the CI rather than HTML output that must be dumped locally.

2021-02-03 15:04 UTC, chrissimpkins commented
> What remains to be done here? I can clean up the commits and split the PR up, the core code can go to master and the amrn tests can be appended to the Armenian PR.

@simoncozens is there anything else that you'd like to see to wrap things up here?

2021-02-03 15:07 UTC, simoncozens commented
Looks good to me!

2021-02-04 03:02 UTC, chrissimpkins commented
> Looks good to me!

Thank you very much for all of your input Simon!  Much appreciated.

2021-02-04 03:04 UTC, chrissimpkins commented
The new shaping regression testing source was opened in https://github.com/googlefonts/googlesans/pull/140 where it is separated from the Armenian test text runs here.

2021-02-05 10:44 UTC, madig commented
I have moved the test code to https://github.com/googlefonts/googlesans/pull/140 and added the test files to https://github.com/googlefonts/googlesans/pull/129. This PR is hereby superseded.

2021-02-05 10:44 UTC, closed without merging