Glyph maintenance
googlefonts/googlesans pull request #307
Opened 2021-06-01 13:11 UTC by madig

Closes #122
Closes https://github.com/googlefonts/googlesans/issues/308
Closes https://github.com/googlefonts/googlesans/issues/152
Closes https://github.com/googlefonts/googlesans/issues/264
Closes https://github.com/googlefonts/googlesans/issues/280.

Also:

- cleans up [18] bracket layer directories

2021-06-03 13:25 UTC, chrissimpkins commented
Will wait on Gurmukhi and Georgian merges to merge this.

2021-06-03 13:58 UTC, madig commented
TTX says no diff when #anchors are removed.

2021-06-03 16:06 UTC, chrissimpkins commented
> TTX says no diff when #anchors are removed.

Good news!  Thanks Nikolaus!

2021-06-08 15:43 UTC, madig commented
@chrissimpkins ping to let you know I axed the logo duplicates and declared the dot-logo variants the one source of truth.

2021-06-08 22:47 UTC, chrissimpkins commented
Changes to address #122: LGTM
Logo forms tested with changes to address #152: LGTM

2021-06-08 22:51 UTC, chrissimpkins commented
Changes to remove #exit Glyphs app specific anchors / address https://github.com/googlefonts/googlesans/issues/308: LGTM

2021-06-09 00:11 UTC, chrissimpkins requested changes
Thanks so much for all of these changes Nikolaus. This looks great.  One minor request to remove outlines from the #280 glyphs that were already in the set.  Otherwise we are gtg here.

2021-06-09 00:11 UTC, chrissimpkins commented on qa/definitions/GoogleSans-Bold.ttf.glyphsetdef
> +uni034F
It looks like the following from #280 are already in the glyph set:

- U+00ad (Soft hyphen)
- U+200C (zero width nonjoiner)
- U+200D (zero width joiner)

For some reason each of these invisible code points have defined outlines.  It won't save a tremendous amount of space but we may as well remove the outlines on those three glyphs as part of this merge.

2021-06-09 08:39 UTC, madig commented on qa/definitions/GoogleSans-Bold.ttf.glyphsetdef
> +uni034F
Done in https://github.com/googlefonts/googlesans/pull/307/commits/d6dc7accd60a01b4b5cc39e833d4db776eac3e49.

2021-06-09 12:32 UTC, chrissimpkins approved these changes
LGTM!  I'll update the changelog and merge this today.  Thank you very much Nikolaus!

2021-06-09 16:00 UTC, chrissimpkins commented
Changelog updated in 5ef39aeb7257be42765eca644ac52cbfbb755f56

2021-06-09 16:01 UTC, chrissimpkins commented
Thanks again Nikolaus!

2021-06-09 16:01 UTC, merged