Import new Berlow two and circled numbers
googlefonts/googlesans pull request #326
Opened 2021-06-25 14:33 UTC by madig

Closes https://github.com/googlefonts/googlesans/issues/322
Closes #269
Supersedes https://github.com/googlefonts/googlesans/pull/311

---

Test strings:

```
➊➋➌➍➎➏➐➑➒
```

```
➀➁➂➃➄➅➆➇➈
```

### TODO

- [x] remove kerning updates in this PR (per D Berlow, there should be no kerning update in numr/dnom forms)
- [x] grade axis is reversed in negative circled figs (https://github.com/googlefonts/googlesans/pull/326#issuecomment-875871303), requires source update before we merge (fixed in https://github.com/googlefonts/googlesans/pull/326/commits/ca2b1d925af926d829fbcf23ca67ab6d3c95305c)

2021-06-27 09:11 UTC, madig commented
PR stapling :D

2021-07-07 18:44 UTC, chrissimpkins commented on scripts/gs-merge-designspace.py
> +    Vendor sources are inconsistent, so using user values and tags to match
What names are inconsistent?  I'll try to address this in advance of the files landing in your hands going forward

2021-07-07 18:50 UTC, chrissimpkins commented
@dberlow It looks like Nikolaus imported new figure kerning with the numr/dnom/circled fig updates.  Should we be importing this kerning from your sources?

2021-07-07 18:54 UTC, chrissimpkins commented
It looks like the addition is `six` kerned with four numerator forms (5,6,9,0).

```diff
<key>six</key>
    <dict>
      <key>five.numerator</key>
      <integer>-10</integer>
      <key>nine.numerator</key>
      <integer>-10</integer>
      <key>public.kern2.GRK_Psi</key>
      <integer>-30</integer>
      <key>public.kern2.GRK_Tau</key>
      <integer>-10</integer>
      <key>public.kern2.GRK_Upsilon</key>
      <integer>-30</integer>
      <key>six.numerator</key>
      <integer>-10</integer>
      <key>zero.numerator</key>
      <integer>-20</integer>
    </dict>
```

2021-07-07 19:16 UTC, chrissimpkins commented
Test strings (for my future reference):

```
➊➋➌➍➎➏➐➑➒
```

```
➀➁➂➃➄➅➆➇➈
```

2021-07-07 19:26 UTC, chrissimpkins commented
@madig Mind checking your import to confirm that we pulled the correct downstream : upstream masters across GRAD for the dingbat negative circled figures (U+278A - U+2792)?

The grade axis range is reversed across these code points. When you head to the negative side of the axis range the forms are heavier and when you head to the positive side of the range they lighten. This occurs across the full design space @ opsz 17 - 18 and wght 400 - 700, Roman and Italic sources.  The behavior should be the opposite.  +GRAD = heavier forms, -GRAD = lighter forms

![circled-figs](https://user-images.githubusercontent.com/4249591/124817201-7390d900-df37-11eb-8aa7-7865d19b7998.gif)

I can confirm that all looks well in the numr, dnom, and frac forms as well as in the dingbat circled sans serif forms (with ring around a figure rather than solid background)

cc @dberlow in case this is in the original sources

2021-07-07 22:07 UTC, chrissimpkins requested changes
- [x] should we be pulling fig:numr kerning pairs? (https://github.com/googlefonts/googlesans/pull/326#issuecomment-875847070) (answer is no from D Berlow)
- [x] grade axis is reversed in negative circled figs (https://github.com/googlefonts/googlesans/pull/326#issuecomment-875871303), requires source update before we merge

2021-07-08 08:52 UTC, madig commented on scripts/gs-merge-designspace.py
> +    Vendor sources are inconsistent, so using user values and tags to match
Axis names, design locations. Deva and Gurm e.g. still had "Optical size" instead of the "Size" we use now because they strted from older sources I think. Berlow didn't have separate design locations, etc.

2021-07-08 14:10 UTC, madig commented
This is in the original sources.

2021-07-08 14:10 UTC, chrissimpkins commented
> This is in the original sources.

Thanks Nikolaus. I really appreciate it.

2021-07-08 15:22 UTC, chrissimpkins commented
> @madig Mind checking your import to confirm that we pulled the correct downstream : upstream masters across GRAD for the dingbat negative circled figures (U+278A - U+2792)?
> 
> The grade axis range is reversed across these code points. When you head to the negative side of the axis range the forms are heavier and when you head to the positive side of the range they lighten. This occurs across the full design space @ opsz 17 - 18 and wght 400 - 700, Roman and Italic sources. The behavior should be the opposite. +GRAD = heavier forms, -GRAD = lighter forms
> 
> ![circled-figs](https://user-images.githubusercontent.com/4249591/124817201-7390d900-df37-11eb-8aa7-7865d19b7998.gif)
> 
> I can confirm that all looks well in the numr, dnom, and frac forms as well as in the dingbat circled sans serif forms (with ring around a figure rather than solid background)
> 
> cc @dberlow in case this is in the original sources

I fixed this by swapping the *.sansSerifBlackCircled GRAD -50 and GRAD 200 designs in Roman and Italic sources @  ca2b1d925af926d829fbcf23ca67ab6d3c95305c. Visually confirmed that this fixes the issue.

@dberlow @sannorozco Please note that your googlefonts/googlesans-fb sources have swapped GRAD masters for this figure set.

2021-07-08 15:23 UTC, chrissimpkins commented
@googlebot I consent.

2021-07-08 15:32 UTC, chrissimpkins approved these changes

2021-07-08 16:47 UTC, chrissimpkins commented
From David Berlow:

> I did not kern the numerators or the denominators

We will need to revert the kerning updates in this pull request. TODO list updated

2021-07-08 17:40 UTC, madig commented
Filtered the kerning changes out.

2021-07-08 17:52 UTC, chrissimpkins commented on source/GoogleSans/gurmukhi.fea
> +lookup gur2_dflt_historical_below_base_consonant_forms {
Addresses https://github.com/googlefonts/googlesans/issues/320

Noting as this was previously merged, closed and seems to change relative to main here.

We must have reverted the original change somewhere along the line?  

Just a note for future reference.

2021-07-08 21:52 UTC, chrissimpkins commented
LGTM.  We will release these updates in v5

2021-07-08 21:53 UTC, chrissimpkins commented
Thanks @madig!

Thanks @dberlow!

2021-07-08 21:53 UTC, merged