Update maintainer doc, split out vendor and style doc
googlefonts/googlesans pull request #382
Opened 2021-09-03 17:12 UTC by belluzj

This is a rebase of the previous #120 that was never merged + some updates I did while working on the Tamil.

It also includes a script update from @madig, I'll let him comment on the usefulness of that when he's back on Tuesday.

2021-09-07 14:15 UTC, madig approved these changes

2021-09-07 17:26 UTC, chrissimpkins reviewed
LGTM. A couple of questions.  I also suggest that we document the glyph deletion workflow and develop a new approach to import over existing glyphs with GRAD axis expansion.

2021-09-07 17:26 UTC, chrissimpkins commented on docs/MAINTAINER.md
> +3. Import the resulting Designspaces into their intended target Designspaces:
```suggestion
3. Import the resulting Designspaces into their intended target Designspaces without GRAD axis support:
```

2021-09-07 17:26 UTC, chrissimpkins commented on docs/MAINTAINER.md
> +4. Check that glyphs, especially ligatures, have the correct production name set. Something like `k_ssa_uMatra-tamil` should have the production name `uni0B950BCD0BB70BC1`. Using Glyphs.app's naming
Does this work if you open UFO in Glyphs app as well as a glyphs formatted source file?

2021-09-08 07:24 UTC, madig commented on docs/MAINTAINER.md
> +4. Check that glyphs, especially ligatures, have the correct production name set. Something like `k_ssa_uMatra-tamil` should have the production name `uni0B950BCD0BB70BC1`. Using Glyphs.app's naming
You don't need to open the font necessarily, it's a static function. It's enough to use Glyphs.app's naming convention.

2021-09-08 07:29 UTC, madig commented on docs/MAINTAINER.md
> +3. Import the resulting Designspaces into their intended target Designspaces:
The import script _does_ import GRAD axes: https://github.com/googlefonts/googlesans/blob/main/scripts/gs-merge-designspace.py#L146-L154. If no GRAD exists, this happens: https://github.com/googlefonts/googlesans/blob/main/scripts/gs-merge-designspace.py#L288-L314

2021-09-08 15:16 UTC, chrissimpkins commented on docs/MAINTAINER.md
> +3. Import the resulting Designspaces into their intended target Designspaces:
I misunderstood.  Ty!

2021-09-08 15:24 UTC, chrissimpkins requested changes

2021-09-08 15:24 UTC, chrissimpkins commented on docs/VENDOR.md
> +### Generating Glpyhs.app Source Files
```suggestion
### Generating Glyphs.app Source Files
```

2021-09-08 15:24 UTC, chrissimpkins commented on docs/VENDOR.md
> +If you work in Glyphs.app and want to generate sources for modification, skip using Glyphs.app's built-in im- and exporter functionality. Instead, run:
```suggestion
If you work in Glyphs.app and want to generate sources for modification, skip using Glyphs.app's built-in importer / exporter functionality. Instead, run:
```

2021-09-08 15:26 UTC, chrissimpkins approved these changes

2021-09-08 15:26 UTC, chrissimpkins commented
@googlebot I consent.

2021-09-08 15:27 UTC, madig commented
Every time you delete a googlebot comment it posts two new ones.

2021-09-08 15:28 UTC, madig commented
@googlebot I consent.

2021-09-08 15:29 UTC, chrissimpkins commented
> Every time you delete a googlebot comment it posts two new ones.

Useful little bot...

I thought it was coming from my commits but it appears not

2021-09-08 15:50 UTC, chrissimpkins commented
Thank you very much for cleaning this up Jany and Nikolaus!  Looks great.  Merging.

2021-09-08 15:50 UTC, merged