Create unified GitHub Actions CI/CD workflow
googlefonts/googlesans pull request #507
Opened 2022-06-24 18:34 UTC by madig

Which passes files around as needed instead of rebuilding fonts for each step.

---

@chrissimpkins edits below

### TODO

- [x] test git commit tag push => release build workflow

2022-06-25 23:00 UTC, madig commented
According to https://github.com/googlefonts/googlesans/actions/runs/2557773318/usage, they actually round up to the full minute for billing. Maybe the lining jobs should be combined, at least ufolint and kernlint.

2022-07-25 15:59 UTC, madig commented
(Rerun succeeded at https://github.com/googlefonts/googlesans/actions/runs/2733193914)

2022-07-26 20:09 UTC, chrissimpkins commented
@madig Will you please update the maintainer documentation with the process to 

- build and CI test variable fonts
- build and CI test static fonts (seems to be triggered through a separate process, similar to our current approach)
- push a branch that uploads static and variable artifacts to the GH file server for testing
- push a new production GitHub release and release archive

with the changes here? Are you proposing a change in any of our current processes?

2022-07-26 20:15 UTC, chrissimpkins commented
I'll test the git commit tag push to execute the updated release workflow

2022-07-29 12:31 UTC, chrissimpkins commented
> @madig Will you please update the maintainer documentation with the process to
> 
> * build and CI test variable fonts
> * build and CI test static fonts (seems to be triggered through a separate process, similar to our current approach)
> * push a branch that uploads static and variable artifacts to the GH file server for testing
> * push a new production GitHub release and release archive
> 
> with the changes here? Are you proposing a change in any of our current processes?

@madig Let me know when you have a chance

2022-07-29 12:40 UTC, chrissimpkins commented
Triggered the updates here with new version git commit tag

https://github.com/googlefonts/googlesans/actions/runs/2760676731

2022-07-29 13:28 UTC, chrissimpkins commented
The git tag push appropriately triggered a release.

2022-07-29 13:32 UTC, chrissimpkins requested changes

2022-07-29 13:32 UTC, chrissimpkins commented on .github/workflows/cicd.yml
> +          draft: false
Mind changing `draft` to `true`?  This is a change from our previous approach. I think you set it this way in a previous round of Actions work (or maybe on GS Thai Loopless?) and it is nice to be able to review the draft automated release before it is an official release.

2022-07-29 13:37 UTC, madig commented
(Will respond later today hopefully)

2022-07-29 15:50 UTC, chrissimpkins commented
> (Will respond later today hopefully)

No rush as long as you aren't blocked on landing this.  Thanks Nikolaus!

2022-08-01 15:21 UTC, merged