Import Gujarati
googlefonts/googlesans pull request #534
Opened 2022-09-28 14:46 UTC by Hoolean

Hello all! This PR tracks #525.

We have rebased on `import-sinhala`, although if Gujarati becomes ready before Sinhala, we can rebase on `main` instead.

Before the branch is ready for review, we must check for any CI warnings or errors. In addition, we will add the shaping tests from @kalapi when they are delivered : )

---

_Closes #525._

2022-09-29 17:26 UTC, Hoolean commented
Hello @kalapi!

Thank you for providing the shaping tests : )

Having updated the glyph sets, it appears that the following glyphs are unreachable:

- /iMatra_anusvara-gujarati.alt01
- /iMatra_reph-gujarati.alt01
- /iMatra_reph_anusvara-gujarati.alt01
- /t_r-gujarati

Do they require a codepoint or feature to make them accessible, or are they not intended to be used?

2022-09-30 11:47 UTC, MariannaPaszkowska commented
@kalapi  Could you please check mark positioning here:
Combining outline issue - design or positioning of component/anchor:
ખુ ખૂ ઘૃ ખ્રૃ ખૄ ઘૄ ગ્રૄ ઙ્ક્ષ ઙ્ઘ ઙ્મ ટ્વ ડ્ન ડ્વ ઢ્ન 
 
<img width="1175" alt="Screenshot 2022-09-30 at 2 42 39 PM" src="https://user-images.githubusercontent.com/22956348/193262378-2a5e0826-02e2-496c-95d4-0a669ae0c483.png">

_Screenshot from Figma_

Could you also confirm if this is intentional:

Component positioning consistency Text vs Regular: 
દ્ગુ

<img width="487" alt="Screenshot 2022-09-30 at 2 09 51 PM" src="https://user-images.githubusercontent.com/22956348/193260954-d2cdc568-15a3-44aa-8bfa-3fbf82dc4f60.png">

_Screenshot from Figma_

cc @chrissimpkins

2022-09-30 16:00 UTC, kalapi commented
@MariannaPaszkowska This is strange, checking now. Thanks for spotting it.

2022-09-30 16:36 UTC, kalapi commented
@MariannaPaszkowska I think this is a Figma issue. Here's a screenshot from Chrome:

Display
<img width="1082" alt="Screenshot 2022-09-30 at 12 34 56 PM" src="https://user-images.githubusercontent.com/15804460/193316645-cc3f52ec-7900-4f66-8592-50e16f71af1c.png">
Text
<img width="1122" alt="Screenshot 2022-09-30 at 12 36 58 PM" src="https://user-images.githubusercontent.com/15804460/193316940-1fc0158e-ae77-4b14-b7a2-91013649666b.png">

I see that the 4th combination above doesn't position correctly but that's an impossible combination, so it's fine. But the others are shaping fine. 

The 2nd issue (દ્ગુ uMatra positioning) is also not a problem on Chrome (Harfbuzz). How do we fix this?

2022-09-30 17:10 UTC, kalapi commented
> Having updated the glyph sets, it appears that the following glyphs are unreachable:
> 
> * /iMatra_anusvara-gujarati.alt01
> * /iMatra_reph-gujarati.alt01
> * /iMatra_reph_anusvara-gujarati.alt01
> * /t_r-gujarati

@Hoolean The attached package fixes the above. 

[2022-09-30_GoogleSansGujarati_V1.000_BETA03.zip](https://github.com/googlefonts/googlesans/files/9686449/2022-09-30_GoogleSansGujarati_V1.000_BETA03.zip)

2022-10-03 06:29 UTC, MariannaPaszkowska commented
Thanks for the update, @kalapi!
I can confirm that this is not a problem on Chrome (Harfbuzz).

<img width="1028" alt="Screenshot 2022-10-03 at 9 21 38 AM" src="https://user-images.githubusercontent.com/22956348/193513185-fc4281d0-8184-4254-9e3d-5b5be306a34f.png">

_Screenshot from Wakamaifondue._



There is an improvement in Figma now, shaping is different, but now other issues have popped up: 
<img width="1118" alt="Screenshot 2022-10-03 at 9 14 32 AM" src="https://user-images.githubusercontent.com/22956348/193512094-d8b28774-f919-4647-b885-618a6ae81b5a.png">

_Screenshot from Figma._

@Hoolean @belluzj Any ideas on what might be causing this and how can we fix it?

2022-10-03 08:12 UTC, belluzj commented
Since you have a special relationship with Figma, would you be able to ask them what version of Harfbuzz they're compiling against in their C++/WASM bundle? They may want to update it if it's old? Just a thought

2022-10-03 14:35 UTC, kalapi commented
@MariannaPaszkowska I can confirm that I haven't touched any of the positioning in the new Gujarati package other than in a few conjuncts not listed above.

2022-10-04 08:38 UTC, MariannaPaszkowska commented
@kalapi I also suspect that it is something Figma-specific. @Hoolean @belluzj We can continue with the production and release. 
I tested GS Gujarati in other environments and can confirm that except for Figma, I see expected behavior:

<img width="584" alt="Screenshot 2022-10-04 at 9 50 25 AM" src="https://user-images.githubusercontent.com/22956348/193773248-91eedcef-6909-41f1-9049-2c8d997915bf.png">

_TextEdit on Apple_  *it was the same for _wakamaifondue and Samsa in Safari.

<img width="766" alt="Screenshot 2022-10-04 at 9 43 40 AM" src="https://user-images.githubusercontent.com/22956348/193773275-3e4f5245-5fda-4c98-8dff-b3be2375d748.png">

_wakamaifondue in Firefox_

cc @chrissimpkins

2022-10-04 15:38 UTC, madig commented
No new GDEF warnings in the VFs compared to Odia.

2022-10-04 16:19 UTC, madig commented
@kalapi can you please test the latest import in Adobe apps again?

2022-10-04 16:46 UTC, madig commented
I believe this is ready for inspection, given that we're ignoring Figma and InDesign seems to work fine?

2022-10-05 14:40 UTC, madig commented
@kalapi can you please reupload the beta3 package with your built fonts? I think they're from beta2?

2022-10-05 14:42 UTC, kalapi commented
Hi @madig let me check and get back to you immediately.

2022-10-05 14:47 UTC, kalapi commented
I checked the fonts and they seem to be generated after I made the changes but i've generated them again in the below package:

[2022-10-05_GoogleSansGujarati_V1.000_BETA03b.zip](https://github.com/googlefonts/googlesans/files/9716606/2022-10-05_GoogleSansGujarati_V1.000_BETA03b.zip)

2022-10-05 17:24 UTC, Hoolean commented
Hello @MariannaPaszkowska, @chrissimpkins,

Nikolaus has merged in the latest fixes (thank you @kalapi!), and Hanna will begin regression testing them tomorrow morning 🚀

2022-10-05 20:12 UTC, chrissimpkins commented
> I believe this is ready for inspection, given that we're ignoring Figma and InDesign seems to work fine?

To be fair, we're not ignoring any environment.  TMK the identified issues are in product-specific font rendering environments, sometimes maybe even in a version-specific way like the issues identified in InDesign by DaMa but unable to be reproduced in InDesign by Kalapi.  Do you have recommendations about how to achieve correct shaping at the font level?  I'm not aware of an identified solution to the issue that seems to be isolated to the Figma environment in the thread here. The plan is to approach the Figma team to report this as a shaping bug in their environment since the layout code WAI in other tested environments.

2022-10-05 20:16 UTC, chrissimpkins commented
OK to merge this before #517 if we complete the review here earlier?

2022-10-06 10:26 UTC, belluzj commented
Hanna is scheduled to check the latest version of InDesign on our side as part of her review today.

About the merge order, any is fine, we'll fix conflicts or rebase the other one, whichever that is. Thanks!

2022-10-06 15:29 UTC, madig commented
@kalapi please see the updated import log with the latest comments. What version of InDesign are you using? Hanna could reproduce the error in 17.3 and 17.4.

2022-10-06 15:52 UTC, kalapi commented
Hi @madig. I have v16 and v17.4 and shaping works on both:

<img width="1009" alt="Screenshot 2022-10-06 at 11 38 10 AM" src="https://user-images.githubusercontent.com/15804460/194359168-8795c45e-df36-4e26-a55e-dd13cbd8046f.png">

<img width="1048" alt="Screenshot 2022-10-06 at 11 46 46 AM" src="https://user-images.githubusercontent.com/15804460/194359188-838ccab2-a00d-4df9-bcd8-08011e2bc209.png">

These are my options for 'Advanced Type':

<img width="858" alt="Screenshot 2022-10-06 at 11 38 51 AM" src="https://user-images.githubusercontent.com/15804460/194359454-71a0c524-6fd5-4900-ad73-a7b20870afd2.png">

Language selection has no effect.

Thanks for updating the import log. I'll look at the other things posted there. 

This may also be interesting although it's from 2 years ago and i'd expect Adobe to activate this by default (but maybe they don't): https://twitter.com/vinodbala/status/1285259248973213696

2022-10-07 00:13 UTC, kalapi commented
@madig I'm attaching a new package based on Hanna's observations.

[2022-10-06_GoogleSansGujarati_V1.000_BETA04.zip](https://github.com/googlefonts/googlesans/files/9729436/2022-10-06_GoogleSansGujarati_V1.000_BETA04.zip)

2022-10-07 06:30 UTC, MariannaPaszkowska commented
@belluzj @madig Any chance we can have this finished today?

2022-10-07 07:13 UTC, madig commented
On it.

2022-10-07 07:52 UTC, madig commented
So, we had the idea that InDesign doesn't seem to work the fonts out of the box because it may expect the older `gujr` shaping model instead of the newer `gujr2` one (various gujr fonts on Google Fonts like Rasa have both and work), but Kalapi only targets Harfbuzz. We good on ignoring InDesign then or requiring users to use the hidden Harfbuzz option?

2022-10-07 07:57 UTC, MariannaPaszkowska commented
@madig Since users can use the hidden Harfbuzz option, and this environment is not our priority, let's proceed using only `gujr2`. 
CC @chrissimpkins

2022-10-07 08:54 UTC, madig commented
I'll see if I can find anyone to cross-check the latest changes on our side.

2022-10-07 09:21 UTC, madig commented
@kalapi Can you please give us a high-level changelog for beta 4? 1106 files are being changed...

2022-10-07 11:38 UTC, chrissimpkins commented
I noticed that the slash.loclTAML still trails all of the new Gujarati glyphs added here. It looks like we have a merge conflict now in https://github.com/googlefonts/googlesans/pull/533.  IIUC the plan will be to merge this, then conflicts in #533 will be addressed and we will merge that?

2022-10-07 11:45 UTC, chrissimpkins requested changes
Missing Apache license on the new Py script

2022-10-07 11:45 UTC, chrissimpkins commented on scripts/one-off/check-script-tags.py
> +import tomli
Please add Apache 2 license header

2022-10-07 11:47 UTC, chrissimpkins commented
Will you please push a build branch so that we can trigger the static font format checks when the import work is completed?

2022-10-07 12:23 UTC, Hoolean commented
Hello @chrissimpkins, yes, I think that makes sense for /slash.loclTAML; we can rebase whichever branch comes second, and having that be #533 seems likes the simplest approach.

On the build, to check I understand correctly: would you like us to make the build- branch after we have cross-checked the latest fixes, or would you prefer us to set this running on the merged sources now?

2022-10-07 12:42 UTC, madig commented
I pushed a branch now: https://github.com/googlefonts/googlesans/actions/runs/3204809760

We can update it as we go.

2022-10-07 13:03 UTC, kalapi commented
> @kalapi Can you please give us a high-level changelog for beta 4? 1106 files are being changed...

Yes ofcourse; 

1. The majority of the changes are from the Medium-italic interpolation where a straight stem didn't have the same start point in almost all of the base glyphs resulting in the following rhomboidal slanted stems:

<img width="662" alt="Screenshot 2022-10-07 at 8 56 18 AM" src="https://user-images.githubusercontent.com/15804460/194559035-fd6032e3-c35c-47f0-9afd-01f456a27b89.png">

2. This also led me to change anchor-positions of the 'bottomright' anchor by a few units to make the connection proper.

The majority of changes are from the top two. Then,

3. Added kerning for a few glyphs

4. Added 4 new glyphs `t-gujarati.alt02`, `t_t-gujarati`, `n-gujarati.alt01`, and `l_ka-gujarati`. 

5. Updated OT layout code to support above glyphs

2022-10-07 15:44 UTC, chrissimpkins commented
> would you like us to make the build- branch after we have cross-checked the latest fixes, or would you prefer us to set this running on the merged sources now?

Only when you feel that the changes are complete and ready for Marianna and I to review. Thanks Harry!

2022-10-07 16:19 UTC, madig commented
Under hopefully final QA now, estimated time 90 mins (because that's when she goes home 😁).

2022-10-07 17:41 UTC, madig commented
Our QA person couldn't finish the review, we'll try to get the original reviewer on it next week... sorry :(

She found one thing though, the interpolation fixes seem to have swapped some outlines (see comment below original interpolation issue in doc).

2022-10-07 18:22 UTC, kalapi commented
> Our QA person couldn't finish the review, we'll try to get the original reviewer on it next week... sorry :(
> 
> She found one thing though, the interpolation fixes seem to have swapped some outlines (see comment below original interpolation issue in doc).

Thanks, will look into it.

2022-10-07 18:51 UTC, kalapi commented
> > Our QA person couldn't finish the review, we'll try to get the original reviewer on it next week... sorry :(
> > She found one thing though, the interpolation fixes seem to have swapped some outlines (see comment below original interpolation issue in doc).
> 
> Thanks, will look into it.

Fixes minor interpolation issues in the the `opsz` axis:

Updated glyphs in the upright master:

```
ભ્ર bh_ra-gujarati
લ્ર l_ra-gujarati
```

Updated glyphs in the italic master:

```
લ la-gujarati
લ્ l-gujarati
ક્લ k_la-gujarati
ઝ્ર jh_ra-gujarati
```

[2022-10-07_GoogleSansGujarati_V1.000_BETA05.zip](https://github.com/googlefonts/googlesans/files/9736464/2022-10-07_GoogleSansGujarati_V1.000_BETA05.zip)

2022-10-10 12:09 UTC, Hoolean commented
Hello @kalapi! Thank you for the speedy turnaround : )

We have made a few assumptions in the merge that we would like to check with you:

### 1) Feature code in upright vs italic

The feature code is different in the upright and italic fonts. We have assumed that the implementation and positioning in upright is preferred, and have used it for both. Is this correct?

##### In upright

```AFDKO
# Positioned after GUJ_dflt_pres_halfFormAlternates
lookup GUJ_dflt_pres_conjunctHalfForms {
	sub t_ta-gujarati halant-gujarati by t_t-gujarati;
	sub t-gujarati [t-gujarati t-gujarati.alt01 t-gujarati.alt02] by t_t-gujarati;
} GUJ_dflt_pres_conjunctHalfForms;
```

##### In italic

```AFDKO
# Positioned before GUJ_dflt_pres_halfFormAlternates
lookup GUJ_dflt_pres_conjunctHalfForms {
	sub t_ta-gujarati halant-gujarati by t_t-gujarati;
} GUJ_dflt_pres_conjunctHalfForms;
```

### 2) Extra glyphs on import list

A few glyphs were included on the import list that were not previously in the script; we could not see any anchor changes, and so have discarded them.

* .notdef
* NULL
* CR
* space
* nbspace
* zerowidthspace
* zerowidthjoiner
* zerowidthnonjoiner
* dottedCircle

2022-10-10 14:16 UTC, kalapi commented
> Hello @kalapi! Thank you for the speedy turnaround : )
> 
> 
> 
> We have made a few assumptions in the merge that we would like to check with you:
> 
> 
> 
> ### 1) Feature code in upright vs italic
> 
> 
> 
> The feature code is different in the upright and italic fonts. We have assumed that the implementation and positioning in upright is preferred, and have used it for both. Is this correct?
> 
> 
> 
> ##### In upright
> 
> 
> 
> ```AFDKO
> 
> # Positioned after GUJ_dflt_pres_halfFormAlternates
> 
> lookup GUJ_dflt_pres_conjunctHalfForms {
> 
> 	sub t_ta-gujarati halant-gujarati by t_t-gujarati;
> 
> 	sub t-gujarati [t-gujarati t-gujarati.alt01 t-gujarati.alt02] by t_t-gujarati;
> 
> } GUJ_dflt_pres_conjunctHalfForms;
> 
> ```
> 
> 
> 
> ##### In italic
> 
> 
> 
> ```AFDKO
> 
> # Positioned before GUJ_dflt_pres_halfFormAlternates
> 
> lookup GUJ_dflt_pres_conjunctHalfForms {
> 
> 	sub t_ta-gujarati halant-gujarati by t_t-gujarati;
> 
> } GUJ_dflt_pres_conjunctHalfForms;
> 
> ```
> 
> 
> 
> ### 2) Extra glyphs on import list
> 
> 
> 
> A few glyphs were included on the import list that were not previously in the script; we could not see any anchor changes, and so have discarded them.
> 
> 
> 
> * .notdef
> 
> * NULL
> 
> * CR
> 
> * space
> 
> * nbspace
> 
> * zerowidthspace
> 
> * zerowidthjoiner
> 
> * zerowidthnonjoiner
> 
> * dottedCircle

Thanks! Both your assumptions are correct. I'll fix this on my end too.

2022-10-10 15:20 UTC, Hoolean commented
Cheers @kalapi, thanks for the confirmation; all merged in now.

> Updated glyphs in the upright master:
> 
> ```
> ભ્ર bh_ra-gujarati
> લ્ર l_ra-gujarati
> ```

I also noticed that /b_ra-gujarati was changed in the upright masters instead of /bh_ra-gujarati, is that all good too? (apologies if feature code means that this is equivalent)

2022-10-10 15:26 UTC, kalapi commented
> Cheers @kalapi, thanks for the confirmation; all merged in now.
> 
> > Updated glyphs in the upright master:
> > ```
> > ભ્ર bh_ra-gujarati
> > લ્ર l_ra-gujarati
> > ```
> 
> I also noticed that /b_ra-gujarati was changed in the upright masters instead of /bh_ra-gujarati, is that all good too? (apologies if feature code means that this is equivalent)

Sorry it's meant to be `બ્ર b_ra-gujarati`, which has indeed been fixed.

2022-10-10 15:31 UTC, Hoolean commented
Super! We will plan the final QA 🚀

2022-10-10 15:52 UTC, MariannaPaszkowska commented
Thank you all! This is our top priority for this week.

2022-10-11 11:21 UTC, Hoolean commented
To update: Alex will be starting the final QA tomorrow morning; we will pass on any feedback as soon as possible :+1:

2022-10-11 21:23 UTC, chrissimpkins commented
> To update: Alex will be starting the final QA tomorrow morning; we will pass on any feedback as soon as possible 👍

Tyvm for the update Harry!

2022-10-13 10:27 UTC, Hoolean commented
@MariannaPaszkowska @chrissimpkins @kalapi

Hello,

Alex's QA has now concluded, with the latest feedback available [here](https://docs.google.com/document/d/1hy_BWuNmJWrbrZ4LOkq-DHvln0FRD35BDVnBEKYiCRc/edit?usp=sharing). In summary, most points have been addressed, although there is a potential issue with kerning, and with matra placement.

(The InDesign and /space issues documented are out-of-scope)

2022-10-13 10:35 UTC, MariannaPaszkowska commented
Thank you, @Hoolean

2022-10-13 10:41 UTC, MariannaPaszkowska commented
@Hoolean Could you point me to where that potential issue with kerning and the issue with matra placement are described?

2022-10-13 11:46 UTC, MariannaPaszkowska commented
@kalapi Thanks for all your hard work so far. DaMa team is reporting that those issues are persisting in Beta 5: 

<img width="680" alt="Screenshot 2022-10-13 at 2 41 29 PM" src="https://user-images.githubusercontent.com/22956348/195587348-e837d6eb-636d-4c9f-83fd-e2fd7fa56433.png">

<img width="655" alt="Screenshot 2022-10-13 at 2 41 55 PM" src="https://user-images.githubusercontent.com/22956348/195587359-5f346ac8-9530-485e-8180-b7cd0857b241.png">

<img width="629" alt="Screenshot 2022-10-13 at 2 42 06 PM" src="https://user-images.githubusercontent.com/22956348/195587386-22976b3c-1874-4201-8f5a-ff50ec972cef.png">

Screenshots were taken from [Google Sans Gujarati Import Log]( https://docs.google.com/document/d/1hy_BWuNmJWrbrZ4LOkq-DHvln0FRD35BDVnBEKYiCRc/edit# )

Could you please explain if this is intentional? 

cc @chrissimpkins

2022-10-13 12:50 UTC, Hoolean commented
@MariannaPaszkowska @chrissimpkins Alex is on standby to absorb the QA tomorrow if we are able to merge new sources for then :+1:

2022-10-13 13:21 UTC, kalapi commented
Hi @MariannaPaszkowska @Hoolean,

1. I can only reproduce the first issue with the GPOS which I've now fixed. 

- Fixes top anchors in `sa-gujarati` and `n_sa-gujarati` 

2. I cannot reproduce the kerning issue. It's fixed in my test fonts in BETA05, here is switching DIST on/off in FontGoggles:

![DIST-ONOFF](https://user-images.githubusercontent.com/15804460/195607166-e7e0c7f9-d6d6-44ad-b862-070807fcdf6b.gif)

3. The third issue is also a false positive, if you inspect my sources, you'll see that the space glyph has the correct value. 

Here is BETA06 with the GPOS fix:

[2022-10-13_GoogleSansGujarati_V1.000_BETA06.zip](https://github.com/googlefonts/googlesans/files/9777045/2022-10-13_GoogleSansGujarati_V1.000_BETA06.zip)

2022-10-13 15:58 UTC, Hoolean commented
Thank you for the new sources @kalapi : ) I will pass them over to Alex, who will conclude the review, and we will aim to get the all-clear tomorrow.

---

> Fixes top anchors in `sa-gujarati` and `n_sa-gujarati`

I noticed in the adjustments that "bottom" and "topright" were removed; is this just from pruning unused anchors?

> I cannot reproduce the kerning issue. It's fixed in my test fonts in BETA05, here is switching DIST on/off in FontGoggles

Yes, this was our mistake, sorry about that; I will ensure we use DIST instead of our kerning toggle when checking these changes.

> The third issue is also a false positive, if you inspect my sources, you'll see that the space glyph has the correct value.

In the beta 6 sources/binaries, the space widths still vary across Display Italic; this may be where the confusion lies, as the values look correct elsewhere. Nevertheless, we do not need to correct this now as it is not imported, so we are safe to leave it as it is.

2022-10-13 16:01 UTC, kalapi commented
Hello

> I noticed in the adjustments that "bottom" and "topright" were removed; is this just from pruning unused anchors?

Yes indeed. Those were artefacts from de-componentisation. 

> > The third issue is also a false positive, if you inspect my sources, you'll see that the space glyph has the correct value.
> 
> In the beta 6 sources/binaries, the space widths still vary across Display Italic; this may be where the confusion lies, as the values look correct elsewhere. Nevertheless, we do not need to correct this now as it is not imported, so we are safe to leave it as it is.

I've fixed this on our side. I figured out the confusion and have incorporated a check for this in future releases. 

Thanks for your patience :)

2022-10-13 18:15 UTC, MariannaPaszkowska commented
Thank you for the speedy turnaround! @kalapi @Hoolean

2022-10-14 10:14 UTC, Hoolean commented
@MariannaPaszkowska @chrissimpkins

Hello!

Alex [has completed the review](https://docs.google.com/document/d/1hy_BWuNmJWrbrZ4LOkq-DHvln0FRD35BDVnBEKYiCRc/edit#bookmark=id.mt7v6pvl2sq3), and all non-InDesign issues have been resolved :tada: Thank you @kalapi!

I have set a build branch running [here](https://github.com/googlefonts/googlesans/actions/runs/3249137456); after we have checked the CI warnings, we will be ready to merge 🚀

2022-10-14 11:18 UTC, Hoolean commented
All CI checks passing; no additional warnings when compared to `main`.

2022-10-14 14:55 UTC, MariannaPaszkowska approved these changes

2022-10-14 14:56 UTC, chrissimpkins commented on scripts/one-off/check-script-tags.py
> +import tomli
Ty!

2022-10-14 18:24 UTC, chrissimpkins commented
Many thanks to all for all of your hard work on this!

2022-10-17 13:12 UTC, chrissimpkins commented on scripts/one-off/check-script-tags.py
> +import tomli
https://github.com/googlefonts/googlesans/pull/534/commits/584f66c8249ab8e0adc8e82bfe73c2d7fd363846

2022-10-17 13:12 UTC, chrissimpkins approved these changes

2022-10-17 16:17 UTC, Hoolean commented
I have rebased on `main`, and now the diffs in the shaping tests all stem from Gujarati. When regenerating the shaping JSONs, we see no changes also : )

I have set a build branch going, and will let you know when we get the all clear there :+1:

2022-10-17 16:55 UTC, Hoolean commented
@MariannaPaszkowska @chrissimpkins

The CI [says all-clear](https://github.com/googlefonts/googlesans/actions/runs/3266777549) following the rebase: no warnings beyond those for Odia 🚀

2022-10-18 10:36 UTC, merged

2022-10-18 10:37 UTC, MariannaPaszkowska commented
Thank you, @kalapi, @Hoolean, @madig, @belluzj, @chrissimpkins! 🎉