Use Designspace v5 format
googlefonts/googlesans pull request #553
Opened 2022-11-08 18:15 UTC by madig

This collects all variable info in one file.

The gs-stat.py script is now redundant.

2022-11-11 21:19 UTC, madig commented
Findings so far:

* The separate Designspaces called the opsz axis "Size" and the gs-stat.py script called it "Optical Size", leading to both names turning up in places in the font. The unified Designspace calls both the same. I suppose this is the right thing to happen.
* The name table is organized differently, as in, things are in different order, but other tables referencing name IDs stay the same, as do the important names in the statics. So I suppose this is not a problem.
* The name table is missing Mac names for some reason; the subsetter cuts them out. It's easy enough to make it stop doing that, though.
* The fvar table shows PostScript names now, which also treat Text and Display as one family. I filled in the PostScript names by hand in the DS, making Text a separate family.
* There is an annoyance described in https://github.com/fonttools/fonttools/issues/2877 and the workaround of adding `elidedfallback="Regular"` adds a redundant name entry to both fonts; which is "wrong" for the italic, but harmless, because the italic VF does not use it.

2024-06-20 11:50 UTC, RickyDaMa commented
Good news: diffenator2 reports no difference in outlines (phew)

[Diffenator2 report (v12.000 vs ds5).zip](https://github.com/user-attachments/files/15912884/Diffenator2.report.v12.000.vs.ds5.zip)

Observations from upright VF TTX diffs:
  - `caretSlopeRise` in `hhea` has changed from 1 to 1000
  - Lots of new `name` entries, I think caused by 7178e10
  - `fvar` instances have postscript names now (GoogleSans-Regular, GoogleSans-Medium, and GoogleSans-Bold)
  - `opsz` changed from "Size" to "Optical Size" in `fvar` (5811df0)

If you want to take a look at the TTFs yourself, they're included in the diffenator report archive

2024-07-02 10:36 UTC, madig commented
I've been looking at the name changes and believe there are no relevant ones. 

1. There are Mac-platform copies of the Windows-platform names now, probably because they aren't dropped anymore, as Ricky pointed out.
2. Various names have changed order
3. Some entries like "Grade" now are not duplicated anymore
4. There are now PostScript names for instances
5. The axis "Size" is now called "Optical Size"
6. The names for the Text-family instances are dropped because they aren't in fvar

2024-11-04 13:05 UTC, RickyDaMa requested changes

2024-11-04 13:05 UTC, RickyDaMa commented on source/GoogleSans/GoogleSans.designspace
> +    <instance name="Google Sans Regular" familyname="Google Sans" stylename="Regular" filename="../../build/GoogleSans/instance_ufo/GoogleSans-Regular.ufo" postscriptfontname="GoogleSans-Regular">
This (and ones like it) should be updated to just be "Regular"

2025-09-09 15:06 UTC, madig commented
I am inclined to recommend to just close this. We'd need more time to adjust import scripts to make this work, plus, Glyphs 2 doesn't support incompatible masters in the same file (and our glyphsLib is a bit old for Glyphs 3 support, so we'd need to update requirements and do regression testing, etc.). We don't gain much.

2026-03-23 12:41 UTC, closed without merging

2026-03-23 12:41 UTC, MariannaPaszkowska commented
We are planning to move to fontc, and DSv5 is not yet supported there.